force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>no experience needed</fullName>
            </value>
            <value>
                <fullName>less than 1 year</fullName>
            </value>
            <value>
                <fullName>1 to 3 years</fullName>
            </value>
            <value>
                <fullName>3 to 5 years</fullName>
            </value>
            <value>
                <fullName>more than 5 years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Mechanics</fullName>
            </value>
            <value>
                <fullName>Medicine</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Leadership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Test_Timing__c.field-meta.xml
<CustomField>
    <fullName>Test_Timing__c</fullName>
    <description>This field is for getting the timing for the testing environment</description>
    <label>Test Timing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>15 mins</fullName>
            </value>
            <value>
                <fullName>30 mins</fullName>
            </value>
            <value>
                <fullName>45 mins</fullName>
            </value>
            <value>
                <fullName>60 mins</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobPicklistController.cls
/**
 * @description       : To extract the picklist field values in job custom object
 * @author            : Rudransh Shukla
 * @group             :
 * @last modified on  : 04-29-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public with sharing class JobPicklistController {
  public List<String> getPicklistValues(
    String objectApiName,
    String fieldName
  ) {
    List<String> picklistValues = new List<String>();

    try {
      Schema.DescribeFieldResult fieldDescribe = Schema.getGlobalDescribe()
        .get(objectApiName)
        .getDescribe()
        .fields.getMap()
        .get(fieldName)
        .getDescribe();
      for (Schema.PicklistEntry entry : fieldDescribe.getPicklistValues()) {
        picklistValues.add(entry.getLabel());
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage()+e.getLineNumber());
    }

    return picklistValues;
  }

  @AuraEnabled
  public static List<String> experienceFieldValues() {

    String fieldName = 'experience__c';
    String objectApiName = 'Job__c';

    JobPicklistController controller = new JobPicklistController();

    List<String> picklistValues = controller.getPicklistValues(
      objectApiName,
      fieldName
    );

    return picklistValues;
  }
  @AuraEnabled
  public static list<string> typePickListValues() {
    String fieldName = 'type__c';
    String objectApiName = 'Job__c';

    JobPicklistController controller = new JobPicklistController();

    List<String> picklistValues = controller.getPicklistValues(objectApiName,fieldName);

    return picklistValues;
}
@AuraEnabled
  public static list<string> IndustryPickListValues() {
    String fieldName = 'Industry__c';
    String objectApiName = 'Job__c';
    JobPicklistController controller = new JobPicklistController();
    List<String> picklistValues = controller.getPicklistValues(objectApiName,fieldName);
    return picklistValues;
}

@AuraEnabled
  public static list<string> TimingsPickListValues() {
    String fieldName = 'Test_Timing__c';
    String objectApiName = 'Job__c';
    JobPicklistController controller = new JobPicklistController();
    List<String> picklistValues = controller.getPicklistValues(objectApiName,fieldName);
    return picklistValues;
  }
}