force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/Job_Applicants__c.object-meta.xml
<CustomObject>
    <description>A junction object to link job__c and candidate_Details__c objects</description>
    <label>Job Applicants</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Applicants__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <label>CandidateId</label>
    <referenceTo>Candidate_Details__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <description>A master detail relation between job object and job_applicants object</description>
    <label>Job_Id</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Options__c/Options__c.object-meta.xml
<CustomObject>
    <description>This object contains a child relationship to Question object and stores the options and answers to the test questions</description>
    <label>Options</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Options Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Options__c/fields/Answers__c.field-meta.xml
<CustomField>
    <fullName>Answers__c</fullName>
    <label>Option</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Options__c/fields/Checkbox__c.field-meta.xml
<CustomField>
    <fullName>Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Correct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Options__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Name__c.field-meta.xml
<CustomField>
    <fullName>Question_Name__c</fullName>
    <description>The user will add the question in this field</description>
    <label>Question Name</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of questions which refers to either objective(MCQ) or subjective</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Objective</fullName>
            </value>
            <value>
                <fullName>Subjective</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Weightage__c.field-meta.xml
<CustomField>
    <fullName>Weightage__c</fullName>
    <label>Weightage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <description>Holds the response of particular question.
Junction object between Job applicant and Questions.</description>
    <label>Response</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Job_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Job_Applicants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Applicants</label>
    <referenceTo>Job_Applicants__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Response__c/fields/Response_Value__c.field-meta.xml
<CustomField>
    <fullName>Response_Value__c</fullName>
    <label>Response Value</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/QuestionsController.cls
/**
 * @description       : questions and options custom object controller class
 * @author            : Rudransh Shukla
 * @group             :
 * @last modified on  : 05-01-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public with sharing class QuestionsController {
  public class responseWrapper {
    @AuraEnabled
    public string candidateResponse { get; set; }
    @AuraEnabled
    public string question { get; set; }
    @AuraEnabled
    public Map<string, boolean> actualResponse { get; set; }
    @AuraEnabled
    public Id questionId { get; set; }
    @AuraEnabled
    public string type { get; set; }
    @AuraEnabled
    public decimal weightage { get; set; }

    public responseWrapper() {
      actualResponse = new Map<string, boolean>();
    }
  }

  @AuraEnabled(cacheable=true)
  public static list<string> questionTypeValue() {
    String fieldName = 'Type__c';
    String objectApiName = 'Question__c';
    JobPicklistController controller = new JobPicklistController();
    List<String> picklistValues = controller.getPicklistValues(
      objectApiName,
      fieldName
    );
    return picklistValues;
  }

  @AuraEnabled
  public static void insertQuestionAndOptions(
    string questionName,
    Decimal weightage,
    string type,
    string optionA,
    string optionB,
    string optionC,
    string optionD,
    boolean checkbox_1,
    boolean checkbox_2,
    boolean checkbox_3,
    boolean checkbox_4,
    Id jobId,
    string answer
  ) {
    try {
      Question__c question = new Question__c();
      question.Question_Name__c = questionName;
      question.Weightage__c = weightage;
      question.Type__c = type;
      question.Job__c = jobId;

      insert question;

      Id questionId = question.Id;
      list<Options__c> optionsList = new List<Options__c>();
      if (question.Type__c == 'Objective') {
        if (String.isNotBlank(optionA)) {
          optionsList.add(
            new Options__c(
              Answers__c = optionA,
              Checkbox__c = checkbox_1,
              Question__c = questionId
            )
          );
        }
        if (String.isNotBlank(optionB)) {
          optionsList.add(
            new Options__c(
              Answers__c = optionB,
              Checkbox__c = checkbox_2,
              Question__c = questionId
            )
          );
        }
        if (String.isNotBlank(optionC)) {
          optionsList.add(
            new Options__c(
              Answers__c = optionC,
              Checkbox__c = checkbox_3,
              Question__c = questionId
            )
          );
        }
        if (String.isNotBlank(optionD)) {
          optionsList.add(
            new Options__c(
              Answers__c = optionD,
              Checkbox__c = checkbox_4,
              Question__c = questionId
            )
          );
        }
      } else if (type == 'Subjective' && String.isNotBlank(answer)) {
        optionsList.add(
          new Options__c(Answers__c = answer, Question__c = questionId)
        );
      }

      if (!optionsList.isEmpty()) {
        insert optionsList;
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
  @AuraEnabled(cacheable=true)
  public static list<Question__c> fetchQuestions(Id jobId) {
    try {
      list<Question__c> questionsList = new List<Question__c>();

      questionsList = [
        SELECT
          id,
          Question_Name__c,
          Type__c,
          Weightage__c,
          (SELECT id, Answers__c, Name, Checkbox__c FROM Options__r)
        FROM Question__c
        WHERE Job__c = :jobId
      ];

      return questionsList;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static string getResponsesAndQuestions(Id jobId, Id candidateId) {
    try {
      List<responseWrapper> result = new List<responseWrapper>();

      List<Job_Applicants__c> jobApplicantsList = [
        SELECT Id
        FROM Job_Applicants__c
        WHERE CandidateId__c = :candidateId AND Job_Id__c = :jobId
        LIMIT 1
      ];

      if (!jobApplicantsList.isEmpty()) {
        Id applicantId = jobApplicantsList[0].Id;

        List<Question__c> questionList = [
          SELECT
            Id,
            Type__c,
            Question_Name__c,
            Weightage__c,
            (SELECT Id, Answers__c, Checkbox__c FROM Options__r),
            (
              SELECT Id, Response_Value__c
              FROM Responses__r
              WHERE Job_Applicants__c = :applicantId
            )
          FROM Question__c
          WHERE Job__c = :jobId
        ];

        for (Question__c ques : questionList) {
          responseWrapper wrapper = new responseWrapper();
          wrapper.question = ques.Question_Name__c;
          wrapper.questionId = ques.Id;
          wrapper.type = ques.Type__c;
          wrapper.weightage = ques.Weightage__c;

          Map<String, Boolean> optionsMap = new Map<String, Boolean>();
          for (Options__c option : ques.Options__r) {
            if (option.Answers__c != null) {
              optionsMap.put(option.Answers__c, false);
            }
            if (option.Checkbox__c != null) {
              optionsMap.put(option.Answers__c, option.Checkbox__c);
            }
          }

          wrapper.actualResponse = optionsMap;
          if (!ques.Responses__r.isEmpty()) {
            wrapper.candidateResponse = ques.Responses__r[0].Response_Value__c;
          }

          result.add(wrapper);
        }
      }
      return JSON.serialize(result);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
  @AuraEnabled
  public static void updateScore(decimal score, id jobid, id candidateid) {
    try {
      list<Job_Applicants__c> applicantList = new List<Job_Applicants__c>();

      List<Job_Applicants__c> queryResult = [
        SELECT Id
        FROM Job_Applicants__c
        WHERE CandidateId__c = :candidateId AND Job_Id__c = :jobId
      ];

      if (!queryResult.isEmpty()) {
        id applicantid = queryResult[0].Id;
        for (Job_Applicants__c applicant : [
          SELECT Total_Score__c, Assesment_Status__c
          FROM Job_Applicants__c
          WHERE id = :applicantid
        ]) {
          applicant.Total_Score__c = score;
          applicant.Assesment_Status__c = 'Evaluated';
          applicantList.add(applicant);
        }
      }

      if (!applicantList.isEmpty()) {
        update applicantList;
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static void deleteQuestion(id questionId) {
    try {
      Question__c question = [
        SELECT id
        FROM Question__c
        WHERE id = :questionId
      ];
      if (question != null) {
        delete question;
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}