force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <description>a brief description about the candidate</description>
    <label>About</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Candidate_Email__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>email of the candidate(unique identifier)</description>
    <inlineHelpText>Your Email address</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city where the candidate is currently residing</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/CTC__c.field-meta.xml
<CustomField>
    <fullName>CTC__c</fullName>
    <inlineHelpText>Your CTC in LPA</inlineHelpText>
    <label>CTC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <inlineHelpText>Add Experience</inlineHelpText>
    <label>Total Experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Prefer Not to say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>Title of the candidate</description>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <description>Picture of the candidate</description>
    <label>Profile Picture</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>skills that would be entered by the candidate</description>
    <inlineHelpText>Enter Comma separated values</inlineHelpText>
    <label>Skills</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>no experience needed</fullName>
            </value>
            <value>
                <fullName>less than 1 year</fullName>
            </value>
            <value>
                <fullName>1 to 3 years</fullName>
            </value>
            <value>
                <fullName>3 to 5 years</fullName>
            </value>
            <value>
                <fullName>more than 5 years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Title_of_position__c.field-meta.xml
<CustomField>
    <fullName>Title_of_position__c</fullName>
    <label>Title of position</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/Job_Applicants__c.object-meta.xml
<CustomObject>
    <description>A junction object to link job__c and candidate_Details__c objects</description>
    <label>Job Applicants</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Applicants__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <label>CandidateId</label>
    <referenceTo>Candidate_Details__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <description>A master detail relation between job object and job_applicants object</description>
    <label>Job_Id</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <description>The total work experience of the candidate which includes</description>
    <label>Work Experience</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experience</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <label>Candidate Name</label>
    <referenceTo>Candidate_Details__c</referenceTo>
    <relationshipLabel>Work Experience</relationshipLabel>
    <relationshipName>Work_Experience</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>city where the candidate worked</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>country where the city was located</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Is_Current_Company__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if it&apos;s you are currently working here.</description>
    <inlineHelpText>Check if it&apos;s you are currently working here.</inlineHelpText>
    <label>Is Current Company?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>Skills that the candidate gained at the job</description>
    <label>Skills</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetApplicantData.cls
/**
* @description       : This class is used for fetching the applcant data and work experience
* @author            : Rudransh Shukla
* @group             :
* @last modified on  : 03-29-2024
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class GetApplicantData {
    @AuraEnabled(cacheable=true)
    public static list<Candidate_Details__c> GetApplicantDataMethod(
        string applicantId
    ) {
        system.debug('applicantId------>' + applicantId);
        list<Candidate_Details__c> candidateDetails = [
            SELECT
            Id,
            About__c,
            City__c,
            Country__c,
            CTC__c,
            Date_of_birth__c,
            Candidate_Email__c,
            Gender__c,
            Name,
            Phone_Number__c,
            Skills__c,
            Experience__c,
            Job_Title__c,
            Profile_Picture__c
            FROM Candidate_Details__c
            WHERE id = :applicantId
        ];
        return candidateDetails;
    }
    
    @AuraEnabled(cacheable=true)
    public static list<Work_Experience__c> GetWorkExperienceData(
        string applicantId
    ) {
        system.debug('applicantId------>' + applicantId);
        list<Work_Experience__c> workExpList = [
            SELECT
            CandidateId__c,
            City__c,
            Country__c,
            CreatedById,
            Name,
            From_Date__c,
            Is_Current_Company__c,
            LastModifiedById,
            Organisation__c,
            Skills__c,
            To_Date__c,
            Id
            FROM Work_Experience__c
            WHERE CandidateId__c = :applicantId
            ORDER BY To_Date__c DESC
        ];
        
        system.debug('workExpList' + workExpList);
        return workExpList;
    }
    
    @AuraEnabled(cacheable = true)
    public static List<Job__c> getAppliedJobById(String candidateId) {
        List<Job__c> appliedJobs = new List<Job__c>();
        try {
            List<Job_Applicants__c> jobApplicants = [
                SELECT Job_Id__c
                FROM Job_Applicants__c
                WHERE CandidateId__c = :candidateId
                LIMIT 1
            ];
            
            Set<Id> jobIds = new Set<Id>();
            for (Job_Applicants__c jobApplicant : jobApplicants) {
                jobIds.add(jobApplicant.Job_Id__c);
            }
            
            appliedJobs = [
                SELECT Title_of_position__c
                FROM Job__c
                WHERE Id IN :jobIds
                LIMIT 1
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return appliedJobs;
    }
   // @AuraEnabled(cacheable=true)
    /*public static List<ContentDocumentLink> getResume(string applicantId) {
        System.debug('applicantId------->' + applicantId);
        List<ContentDocumentLink> cdls = new List<ContentDocumentLink>();
        try {
            cdls = [
                SELECT ContentDocumentId
                FROM ContentDocumentLink
                WHERE LinkedEntityId = :applicantId
            ];
        } catch (Exception e) {
            system.debug(e.getMessage() + e.getLineNumber());
        }
        system.debug('cdls------->' + cdls);
        return cdls;
    }*/
@AuraEnabled(cacheable=true)
    public static ApplicantDetailsWrapper getResume(Id applicantId) {
        ApplicantDetailsWrapper wrapper = new ApplicantDetailsWrapper();
        
        // Query to retrieve related notes and attachments for the selected job applicant
        List<ContentDocumentLink> documentLinks = [SELECT ContentDocumentId, LinkedEntityId 
                                                   FROM ContentDocumentLink 
                                                   WHERE LinkedEntityId = :applicantId];
        
        Set<Id> documentIds = new Set<Id>();
        for(ContentDocumentLink link : documentLinks) {
            documentIds.add(link.ContentDocumentId);
        }
        
        List<ContentDocument> documents = [SELECT Id, Title, FileType, ContentSize, LatestPublishedVersionId 
                                           FROM ContentDocument 
                                           WHERE Id IN :documentIds];

        for(ContentDocument document : documents) {
            wrapper.documents.add(new ContentDocumentWrapper(document.Id, document.Title, document.FileType, document.ContentSize, document.LatestPublishedVersionId));
        }
        system.debug('wrapper------------------>'+ wrapper);
        return wrapper;
    }
    
    // Wrapper class to hold related notes and attachments data
    public class ApplicantDetailsWrapper {
        @AuraEnabled public List<ContentDocumentWrapper> documents { get; set; }
        
        public ApplicantDetailsWrapper() {
            documents = new List<ContentDocumentWrapper>();
        }
    } 
    // Wrapper class for ContentDocument
    public class ContentDocumentWrapper {
        @AuraEnabled public Id Id { get; set; }
        @AuraEnabled public String Title { get; set; }
        @AuraEnabled public String FileType { get; set; }
        @AuraEnabled public Integer ContentSize { get; set; }
        @AuraEnabled public Id LatestPublishedVersionId { get; set; }
        
        public ContentDocumentWrapper(Id Id, String Title, String FileType, Integer ContentSize, Id LatestPublishedVersionId) {
            this.Id = Id;
            this.Title = Title;
            this.FileType = FileType;
            this.ContentSize = ContentSize;
            this.LatestPublishedVersionId = LatestPublishedVersionId;
        }
    }
}