force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/Candidate_Email__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>email of the candidate(unique identifier)</description>
    <inlineHelpText>Your Email address</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/registerCandidateController.cls
/**
 * @description       : insert candidate data in records
 * @author            : Rudransh Shukla
 * @group             :
 * @last modified on  : 03-06-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public without sharing class registerCandidateController {
    @AuraEnabled
  public static void candidateResgisterMethod(
    string firstName,
    String lastName,
    string email,
    string password
  ) {
    try {
      list<Candidate_Details__c> candidateList = new List<Candidate_Details__c>();
      Candidate_Details__c candidate = new Candidate_Details__c();

      candidate.Name = firstName + ' ' + lastName;
      candidate.Candidate_Email__c = email;
      candidate.Password__c = password;

      candidateList.add(candidate);
      if (!candidateList.isEmpty()) {
        insert candidate;
      }
    } catch (Exception e) {
      system.debug(
        'errror------>' + e.getMessage() + '------->' + e.getLineNumber()
      );
    }
  }
}