force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidate_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Test_Timing__c.field-meta.xml
<CustomField>
    <fullName>Test_Timing__c</fullName>
    <description>This field is for getting the timing for the testing environment</description>
    <label>Test Timing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>15 mins</fullName>
            </value>
            <value>
                <fullName>30 mins</fullName>
            </value>
            <value>
                <fullName>45 mins</fullName>
            </value>
            <value>
                <fullName>60 mins</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/Job_Applicants__c.object-meta.xml
<CustomObject>
    <description>A junction object to link job__c and candidate_Details__c objects</description>
    <label>Job Applicants</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Options__c/Options__c.object-meta.xml
<CustomObject>
    <description>This object contains a child relationship to Question object and stores the options and answers to the test questions</description>
    <label>Options</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Options Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Options__c/fields/Answers__c.field-meta.xml
<CustomField>
    <fullName>Answers__c</fullName>
    <label>Option</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Options__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <description>Holds the response of particular question.
Junction object between Job applicant and Questions.</description>
    <label>Response</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Job_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Job_Applicants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Applicants</label>
    <referenceTo>Job_Applicants__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/testingEnvironmentControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */

@isTest
private class testingEnvironmentControllerTest {
  @isTest
  static void TestGetTestTimings() {
    Job__c job = TestDataFactory.createJob();
    job.Test_Timing__c = '15 mins';
    update job;

    string result = testingEnvironmentController.getTestTimings(job.id);

    System.assert(result != null);
    System.assertEquals('15 mins', result);
  }

  @isTest
  static void TestFetchQuestions() {
    Job__c job = TestDataFactory.createJob();
    List<Question__c> questions = TestDataFactory.createSubjectiveQuestion(
      job.id
    );
    list<Options__c> options = TestDataFactory.createSubjectiveOptions(
      questions[0].id
    );
    list<Question__c> result = testingEnvironmentController.fetchQuestions(
      job.id
    );
    System.assert(result.size() == 1);
  }

  @isTest
  static void TestGetObjectiveResponse() {
    Job__c job = TestDataFactory.createJob();
    user u = TestDataFactory.createDummyUser();
    Candidate_Details__c candidate = TestDataFactory.createCandidateDetails();
    candidate.user__c = u.id;
    update candidate;
    Job_Applicants__c applicant = TestDataFactory.createJobApplicant(
      candidate.id,
      job.id
    );
    list<Question__c> question = TestDataFactory.createSubjectiveQuestion(
      job.id
    );
    list<options__c> options = TestDataFactory.createSubjectiveOptions(
      question[0].id
    );

    List<id> optionId = new List<id>{ options[0].id };

    Test.startTest();
    testingEnvironmentController.getObjectiveResponse(optionId, u.id, job.id);
    Test.stopTest();

    integer result = [
      SELECT COUNT()
      FROM Response__c
      WHERE Question__c = :question[0].id
    ];
    System.debug(result);
    System.assert(result != 0);
  }

  @isTest
  static void TestGetSubjectiveResponse() {
    Job__c job = TestDataFactory.createJob();
    user u = TestDataFactory.createDummyUser();
    Candidate_Details__c candidate = TestDataFactory.createCandidateDetails();
    candidate.user__c = u.id;
    update candidate;
    Job_Applicants__c applicant = TestDataFactory.createJobApplicant(
      candidate.id,
      job.id
    );
    list<Question__c> question = TestDataFactory.createSubjectiveQuestion(
      job.id
    );
    list<options__c> options = TestDataFactory.createSubjectiveOptions(
      question[0].id
    );

    Map<id, string> subjectiveResponseMap = new Map<id, string>();
    subjectiveResponseMap.put(question[0].Id, options[0].Answers__c);

    Test.startTest();
    testingEnvironmentController.getSubjectiveResponse(
      u.id,
      subjectiveResponseMap
    );
    Test.stopTest();

    System.assert(
      [SELECT COUNT() FROM Response__c WHERE Question__c = :question[0].id] != 0
    );
  }

  @isTest
  static void TestChangeAssesmentStatus() {
    Job__c job = TestDataFactory.createJob();

    user u = TestDataFactory.createDummyUser();

    Candidate_Details__c candidate = TestDataFactory.createCandidateDetails();
    candidate.user__c = u.id;
    update candidate;

    Job_Applicants__c applicant = TestDataFactory.createJobApplicant(
      candidate.id,
      job.id
    );

    testingEnvironmentController.changeAssesmentStatus(u.id, job.id);

    string result;

    for (Job_Applicants__c app : [
      SELECT Assesment_Status__c
      FROM Job_Applicants__c
      WHERE id = :applicant.id
    ]) {
      result = app.Assesment_Status__c;
    }

    System.assert(result == 'Given');
  }

  @isTest
  static void TestGetAssesmentStatus() {
    Job__c job = TestDataFactory.createJob();
    user u = TestDataFactory.createDummyUser();

    Candidate_Details__c candidate = TestDataFactory.createCandidateDetails();
    candidate.user__c = u.id;
    update candidate;

    Job_Applicants__c applicant = TestDataFactory.createJobApplicant(
      candidate.id,
      job.id
    );
    applicant.Assesment_Status__c = 'Given';
    update applicant;

    string result = testingEnvironmentController.getAssesmentStatus(
      u.id,
      job.id
    );

    System.assert(result == 'Given');
  }

  @isTest
  static void TestGetFeedbackFromCandidate() {
    Job__c job = TestDataFactory.createJob();
    user u = TestDataFactory.createDummyUser();

    Candidate_Details__c candidate = TestDataFactory.createCandidateDetails();
    candidate.user__c = u.id;
    update candidate;

    Job_Applicants__c applicant = TestDataFactory.createJobApplicant(
      candidate.id,
      job.id
    );

    string feedback = 'Testing';
    string result;

    testingEnvironmentController.getFeedbackFromCandidate(
      feedback,
      u.id,
      job.id
    );

    for (Job_Applicants__c applicants : [
      SELECT Feedback__c
      FROM Job_Applicants__c
      WHERE id = :applicant.id
    ]) {
      result = applicants.Feedback__c;
    }

    System.assert(result == feedback);
  }
}