force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city where the candidate is currently residing</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidate_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Name__c/Company_Name__c.object-meta.xml
<CustomObject>
    <label>Company Name</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Title_of_position__c.field-meta.xml
<CustomField>
    <fullName>Title_of_position__c</fullName>
    <label>Title of position</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/Job_Applicants__c.object-meta.xml
<CustomObject>
    <description>A junction object to link job__c and candidate_Details__c objects</description>
    <label>Job Applicants</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Applicants__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Decides the status of the applicant</description>
    <label>Application Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CandidateAppliedJobsControllerTest.cls
@isTest
public class CandidateAppliedJobsControllerTest {
    static TestMethod void testGetAppliedJobs() {
        
        User testUser = TestDataFactory.createDummyUser();
        Candidate_Details__c testCandidate = TestDataFactory.createCandidateDetails();
        testCandidate.User__c = testUser.Id;
        update testCandidate;
        Job__c testJob = TestDataFactory.createJob();
        Job_Applicants__c testJobApplicant = TestDataFactory.createJobApplicant(testCandidate.Id, testJob.Id);
        system.debug('testJobApplicant----->'+ testJobApplicant);
        CandidateAppliedJobsController.JobWrapper result = CandidateAppliedJobsController.getAppliedJobs('', '', testUser.Id, '');
        system.debug('result.jobWrapperList----->'+ result.jobWrapperList);
        System.assertEquals(1, result.jobWrapperList.size());
        
        
        CandidateAppliedJobsController.JobListWrapper jobWrapper = result.jobWrapperList[0];
        System.assertEquals(testJob.Id, jobWrapper.jobId);
        System.assertEquals('Sales Manager', jobWrapper.title);
        System.assertEquals('ABC', jobWrapper.company);
        System.assertEquals('Temporary', jobWrapper.jobType);
        System.assertEquals('Gurgaon', jobWrapper.city);
        System.assertEquals('India', jobWrapper.country);
        System.assertEquals('Pending', jobWrapper.status);
        System.assertEquals(false, jobWrapper.questionsPresent);
        System.assertEquals(false, jobWrapper.assesmentStatus);
    }
    
    static TestMethod void testGetPendingJobListForHomePage() {
        
        User testUser = TestDataFactory.createDummyUser();
        Candidate_Details__c testCandidate = TestDataFactory.createCandidateDetails();
         testCandidate.User__c = testUser.Id;
        update testCandidate;
        Job__c testJob = TestDataFactory.createJob();
        Job_Applicants__c testJobApplicant = TestDataFactory.createJobApplicant(testCandidate.Id, testJob.Id);
        
        
        List<Job__c> result = CandidateAppliedJobsController.getPendingJobListForHomePage(testUser.Id);
		system.debug('result---->'+ result);        
        
        System.assertEquals(1, result.size());
        System.assertEquals(testJob.Id, result[0].Id);
        System.assertEquals('Sales Manager', result[0].Title_of_position__c);
        System.assertEquals('ABC', result[0].Company_Name__c);
        System.assertEquals('Gurgaon', result[0].City__c);
        System.assertEquals('India', result[0].Country__c);
        System.assertEquals('Temporary', result[0].Type__c);
    }
    
    static TestMethod void testGetAppliedJobListForHomePage() {
        
        User testUser = TestDataFactory.createDummyUser();
        Candidate_Details__c testCandidate = TestDataFactory.createCandidateDetails();
        testCandidate.User__c = testUser.Id;
        update testCandidate;
        Job__c testJob = TestDataFactory.createJob();
        Job_Applicants__c testJobApplicant = TestDataFactory.createJobApplicant(testCandidate.Id, testJob.Id);
        testJobApplicant.Application_Status__c='Accepted';
        update testJobApplicant;
        List<Job__c> result = CandidateAppliedJobsController.getAppliedJobListForHomePage(testUser.Id);
        System.assertEquals(1, result.size());
        System.assertEquals(testJob.Id, result[0].Id);
        System.assertEquals('Sales Manager', result[0].Title_of_position__c);
        System.assertEquals('ABC', result[0].Company_Name__c);
        System.assertEquals('Gurgaon', result[0].City__c);
        System.assertEquals('India', result[0].Country__c);
        System.assertEquals('Temporary', result[0].Type__c);
       
    }
    
    static TestMethod void testNumberOfShorlistedJobs() {
        
        User testUser = TestDataFactory.createDummyUser();
        Candidate_Details__c testCandidate = TestDataFactory.createCandidateDetails();
         testCandidate.User__c = testUser.Id;
        update testCandidate;
        Job__c testJob = TestDataFactory.createJob();
        Job_Applicants__c testJobApplicant = TestDataFactory.createJobApplicant(testCandidate.Id, testJob.Id);
        testJobApplicant.Application_Status__c = 'Accepted';
        update testJobApplicant;
        
        
        Integer result = CandidateAppliedJobsController.numberOfShorlistedJobs(testUser.Id);
        
        
        System.assertEquals(1, result);
    }
    
    static TestMethod void testNumberOfPendingJobs() {
        
        User testUser = TestDataFactory.createDummyUser();
        Candidate_Details__c testCandidate = TestDataFactory.createCandidateDetails();
         testCandidate.User__c = testUser.Id;
        update testCandidate;
        Job__c testJob = TestDataFactory.createJob();
        Job_Applicants__c testJobApplicant = TestDataFactory.createJobApplicant(testCandidate.Id, testJob.Id);
        testJobApplicant.Application_Status__c = 'Pending';
        update testJobApplicant;
        
        
        Integer result = CandidateAppliedJobsController.numberOfPendingJobs(testUser.Id);
        
        
        System.assertEquals(1, result);
    }
}