force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/Candidate_Email__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>email of the candidate(unique identifier)</description>
    <inlineHelpText>Your Email address</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <inlineHelpText>Add Experience</inlineHelpText>
    <label>Total Experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>skills that would be entered by the candidate</description>
    <inlineHelpText>Enter Comma separated values</inlineHelpText>
    <label>Skills</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/populateCandidateObject.cls
/**
 * @description       : populate the candidate object based on data from UI
 * @author            : Rudransh Shukla
 * @group             :
 * @last modified on  : 01-02-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public with sharing class populateCandidateObject {
  @AuraEnabled(cacheable=true)
  public static void populateCandidateObjectMethod(string name, integer experience, string skills, string email) {
    
    system.debug('name--->' + name);
    system.debug('skills--->' + skills);
    system.debug('email------>' + email);

    try {
      list<Candidate_Details__c> candidateList = [select name, Experience__c, Skills__c, Candidate_Email__c from Candidate_Details__c limit 1];

      Candidate_Details__c newCandidate = new Candidate_Details__c();

      newCandidate.Name = name;
      newCandidate.Experience__c = experience;
      newCandidate.Skills__c = skills;
      newCandidate.Candidate_Email__c = email;

      candidateList.add(newCandidate);

      if (!candidateList.isEmpty()) {
        insert candidateList;
      }
    }
    catch(Exception e){
        system.debug('errror------>'+e.getMessage()+'------->'+e.getLineNumber());
    }
  }
}