force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <description>a brief description about the candidate</description>
    <label>About</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Candidate_Email__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>email of the candidate(unique identifier)</description>
    <inlineHelpText>Your Email address</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city where the candidate is currently residing</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <inlineHelpText>Add Experience</inlineHelpText>
    <label>Total Experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/ParsedSkills__c.field-meta.xml
<CustomField>
    <fullName>ParsedSkills__c</fullName>
    <label>ParsedSkills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>skills that would be entered by the candidate</description>
    <inlineHelpText>Enter Comma separated values</inlineHelpText>
    <label>Skills</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Company_Name__c/Company_Name__c.object-meta.xml
<CustomObject>
    <label>Company Name</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Job Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>no experience needed</fullName>
            </value>
            <value>
                <fullName>less than 1 year</fullName>
            </value>
            <value>
                <fullName>1 to 3 years</fullName>
            </value>
            <value>
                <fullName>3 to 5 years</fullName>
            </value>
            <value>
                <fullName>more than 5 years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/External_Application_Link__c.field-meta.xml
<CustomField>
    <fullName>External_Application_Link__c</fullName>
    <label>External Application Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Mechanics</fullName>
            </value>
            <value>
                <fullName>Medicine</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Leadership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Publish_end_date__c.field-meta.xml
<CustomField>
    <fullName>Publish_end_date__c</fullName>
    <label>Publish end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Publish_start_date__c.field-meta.xml
<CustomField>
    <fullName>Publish_start_date__c</fullName>
    <label>Publish start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Skills_Required__c.field-meta.xml
<CustomField>
    <fullName>Skills_Required__c</fullName>
    <inlineHelpText>Enter comma separated values</inlineHelpText>
    <label>Skills Required</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Company Overview</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Title_of_position__c.field-meta.xml
<CustomField>
    <fullName>Title_of_position__c</fullName>
    <label>Title of position</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/Job_Applicants__c.object-meta.xml
<CustomObject>
    <description>A junction object to link job__c and candidate_Details__c objects</description>
    <label>Job Applicants</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Applicants__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Decides the status of the applicant</description>
    <label>Application Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <label>CandidateId</label>
    <referenceTo>Candidate_Details__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <description>A master detail relation between job object and job_applicants object</description>
    <label>Job_Id</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobApplicantController.cls
/**
 * @description       : controller for job Applicants custom object
 * @author            : Rudransh Shukla
 * @group             :
 * @last modified on  : 04-12-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public with sharing class JobApplicantController {
  public class applicantWrapper {
    @AuraEnabled
    public List<Candidate_Details__c> candidateDetails { get; set; }
    @AuraEnabled
    public string jobName { get; set; }
    @AuraEnabled
    public id jobId { get; set; }
  }

  public class CandidateWrapper {
    @AuraEnabled
    public Integer matchPercentage { get; set; }
    @AuraEnabled
    public String About { get; set; }
    @AuraEnabled
    public String Candidate_Email { get; set; }
    @AuraEnabled
    public String City { get; set; }
    @AuraEnabled
    public String Country { get; set; }
    @AuraEnabled
    public Id CreatedById { get; set; }
    @AuraEnabled
    public Decimal Experience { get; set; }
    @AuraEnabled
    public Id LastModifiedById { get; set; }
    @AuraEnabled
    public String Name { get; set; }
    @AuraEnabled
    public Id OwnerId { get; set; }
    @AuraEnabled
    public String Phone_Number { get; set; }
    @AuraEnabled
    public String Skills { get; set; }
    @AuraEnabled
    public String Id { get; set; }
    @AuraEnabled
    public boolean isAccepted { get; set; }
    @AuraEnabled
    public string Status { get; set; }
    @AuraEnabled
    public string AssesmentStatus { get; set; }

    public CandidateWrapper(
      Candidate_Details__c candidate,
      Integer matchPercentage,
      String Status,
      String AssesmentStatus
    ) {
      this.matchPercentage = matchPercentage;
      this.About = candidate.About__c;
      this.Candidate_Email = candidate.Candidate_Email__c;
      this.City = candidate.City__c;
      this.Country = candidate.Country__c;
      this.CreatedById = candidate.CreatedById;
      this.Experience = candidate.Experience__c;
      this.LastModifiedById = candidate.LastModifiedById;
      this.Name = candidate.Name;
      this.OwnerId = candidate.OwnerId;
      this.Phone_Number = candidate.Phone_Number__c;
      this.Skills = candidate.Skills__c;
      this.Id = candidate.Id;
      this.isAccepted = false;
      this.Status = Status;
      this.AssesmentStatus = assesmentStatus;
    }
  }
  @AuraEnabled(cacheable=true)
  public static List<CandidateWrapper> fetchCandidateNames(id jobId) {
    List<Job_Applicants__c> candidateIdList = new List<Job_Applicants__c>();
    List<CandidateWrapper> candidateRecords = new List<CandidateWrapper>();

    // Required Skills of job
    List<Job__c> jobs = [
      SELECT Skills_Required__c
      FROM Job__c
      WHERE Id = :jobId
    ];
    Set<String> requiredSkills = new Set<String>();
    for (Job__c job : jobs) {
      if (String.isNotBlank(job.Skills_Required__c)) {
        requiredSkills.addAll(job.Skills_Required__c.split(','));
      }
    }
    for (Job_Applicants__c applicant : [
      SELECT CandidateId__c
      FROM Job_Applicants__c
      WHERE Job_Id__c = :jobId
    ]) {
      candidateIdList.add(applicant);
    }
    List<Id> candidateIds = new List<Id>();
    for (Job_Applicants__c applicant : candidateIdList) {
      candidateIds.add(applicant.CandidateId__c);
    }
    for (Candidate_Details__c candidate : [
      SELECT
        Id,
        About__c,
        Candidate_Email__c,
        City__c,
        Country__c,
        CreatedById,
        Experience__c,
        LastModifiedById,
        Name,
        OwnerId,
        Phone_Number__c,
        Skills__c,
        ParsedSkills__c
      FROM Candidate_Details__c
      WHERE Id IN :candidateIds
    ]) {
      Set<String> candidateSkills = new Set<String>();
      if (String.isNotBlank(candidate.Skills__c)) {
        candidateSkills.addAll(candidate.Skills__c.split(';'));
      }
      Integer matchPercentage = calculateMatchPercentage(
        requiredSkills,
        candidateSkills,
        candidate.ParsedSkills__c
      );
      string Status = getApplicantStatus(candidate.Id, jobId);
      System.debug('status assessment--->' + Status);
      string assessmentStatus = getAssessmentStatus(candidate.Id);

      candidateRecords.add(
        new CandidateWrapper(
          candidate,
          matchPercentage,
          status,
          assessmentStatus
        )
      );
    }
    return candidateRecords;
  }
  @AuraEnabled(cacheable=true)
  public static List<applicantWrapper> getApplicantsList(id userId) {
     List<applicantWrapper> appliedCandidateWrapperList = new List<applicantWrapper>();
    List<Candidate_Details__c> appliedCandidateDetailsList = new List<Candidate_Details__c>();
    string jobName = '';
    user u = [SELECT companyName FROM user WHERE id = :userId LIMIT 1];
    string companyname = u.CompanyName;
    try {
      List<Job_Applicants__c> applicantList = [
        SELECT CandidateId__c, Job_Id__c
        FROM Job_Applicants__c
        WHERE
          Application_Status__c = 'Pending'
          AND Job_Id__c IN (
            SELECT id
            FROM Job__c
            WHERE Company_Name__c = :companyname
          )
        LIMIT 3
      ];

      List<Id> candidateIds = new List<Id>();
      List<Id> jobIds = new List<Id>();
      for (Job_Applicants__c applicant : applicantList) {
        candidateIds.add(applicant.CandidateId__c);
        jobIds.add(applicant.Job_Id__c);
      }
      if (!candidateIds.isEmpty()) {
        appliedCandidateDetailsList = [
          SELECT Name, Candidate_Email__c, City__c, Country__c, Experience__c
          FROM Candidate_Details__c
          WHERE Id IN :candidateIds
        ];
      }

      Map<Id, Candidate_Details__c> candidateMap = new Map<Id, Candidate_Details__c>(
        [
          SELECT
            Id,
            Name,
            Candidate_Email__c,
            City__c,
            Country__c,
            Experience__c,
            About__c,
            Skills__c,
            Phone_Number__c
          FROM Candidate_Details__c
          WHERE Id IN :candidateIds
        ]
      );

      Map<Id, Job__c> jobMap = new Map<Id, Job__c>(
        [
          SELECT Id, Title_of_position__c
          FROM Job__c
          WHERE Id IN :jobIds
        ]
      );

      for (Job_Applicants__c applicant : applicantList) {
        Candidate_Details__c candidate = candidateMap.get(
          applicant.CandidateId__c
        );
        Job__c job = jobMap.get(applicant.Job_Id__c);

        applicantWrapper wrapper = new applicantWrapper();
        wrapper.candidateDetails = new List<Candidate_Details__c>();
        wrapper.candidateDetails.add(candidate);
        wrapper.jobName = job.Title_of_position__c;
        wrapper.jobId = job.Id;

        appliedCandidateWrapperList.add(wrapper);
      }
      System.debug('appliedCandidateWrapperList-------->'+appliedCandidateWrapperList);
      return appliedCandidateWrapperList;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
  @AuraEnabled(cacheable=true)
  public static integer getNumberOfJobsPosted(id userId) {
    user u = [SELECT companyName FROM user WHERE id = :userId LIMIT 1];
    string companyname = u.CompanyName;
    return [
      SELECT COUNT()
      FROM Job__c
      WHERE Status__c = 'Completed' AND Company_Name__c = :companyname
    ];
  }

  @AuraEnabled(cacheable=true)
  public static integer getNumberOfApplicants(id userId) {
    user u = [SELECT companyName FROM user WHERE id = :userId LIMIT 1];
    string companyname = u.CompanyName;
    return [
      SELECT COUNT()
      FROM Job_Applicants__c
      WHERE Job_Id__r.Company_Name__c = :companyName
    ];
  }

  @AuraEnabled(cacheable=true)
  public static list<job__c> fetchJobDetails(string jobId) {
    list<Job__c> jobList = new List<Job__c>();
    try {
      for (Job__c job : [
        SELECT
          Id,
          City__c,
          Company_Name__c,
          Country__c,
          CreatedById,
          Description__c,
          Experience__c,
          External_Application_Link__c,
          Industry__c,
          Name,
          LastModifiedById,
          Location__c,
          OwnerId,
          Publish_end_date__c,
          Publish_start_date__c,
          Salary__c,
          Status__c,
          Summary__c,
          Title_of_position__c,
          Type__c
        FROM Job__c
        WHERE id = :jobId
      ]) {
        jobList.add(job);
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
    return jobList;
  }
  @AuraEnabled
  public static void changeStatus(
    String value,
    List<Id> applicantId,
    id jobId
  ) {
    List<Job_Applicants__c> applicantListToUpdate = new List<Job_Applicants__c>();

    try {
      List<Job_Applicants__c> applicants = [
        SELECT Id, Application_Status__c
        FROM Job_Applicants__c
        WHERE CandidateId__c IN :applicantId AND Job_Id__c = :jobId
      ];
      for (Job_Applicants__c applicant : applicants) {
        applicant.Application_Status__c = value;
        applicantListToUpdate.add(applicant);
      }
      if (!applicantListToUpdate.isEmpty()) {
        update applicantListToUpdate;
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static string getApplicantStatus(id applicantId, id jobId) {
    string status;
    for (Job_Applicants__c applicant : [
      SELECT Application_Status__c
      FROM Job_Applicants__c
      WHERE CandidateId__c = :applicantId AND Job_Id__c = :jobId
    ]) {
      status = applicant.Application_Status__c;
    }
    return status;
  }

  public static string getAssessmentStatus(id applicantId) {
    string status;
    for (Job_Applicants__c applicant : [
      SELECT Assesment_Status__c
      FROM Job_Applicants__c
      WHERE CandidateId__c = :applicantId
    ]) {
      status = applicant.Assesment_Status__c;
    }
    return status;
  }

  @AuraEnabled(cacheable=true)
  public static decimal getScore(id jobid, id candidateid) {
    Decimal score;
    id applicantid = [
      SELECT id
      FROM Job_Applicants__c
      WHERE CandidateId__c = :candidateid AND Job_Id__c = :jobid
    ][0]
    .id;
    for (Job_Applicants__c applicant : [
      SELECT Total_Score__c
      FROM Job_Applicants__c
      WHERE CandidateId__c = :applicantid
    ]) {
      score = applicant.Total_Score__c;
    }
    return score;
  }

  @TestVisible
  private static Integer calculateMatchPercentage(
    Set<String> requiredSkills,
    Set<String> candidateSkills,
    String resumeParsedSkills
  ) {
    List<String> candidateSkillsLower = new List<String>();
    if (String.isNotBlank(resumeParsedSkills)) {
      resumeParsedSkills = resumeParsedSkills.deleteWhitespace().toLowerCase();
    }
    for (String skill : candidateSkills) {
      candidateSkillsLower.add(skill.deleteWhitespace().toLowerCase());
    }
    List<String> requiredSkillsLower = new List<String>();
    for (String skill : requiredSkills) {
      requiredSkillsLower.add(skill.deleteWhitespace().toLowerCase());
    }
    Integer commonSkillsCount = 0;
    for (String skill : requiredSkillsLower) {
      Pattern pattern = Pattern.compile(Pattern.quote(skill));
      Matcher matcher = pattern.matcher(
        candidateSkillsLower.toString() + resumeParsedSkills
      );
      if (matcher.find()) {
        commonSkillsCount++;
      }
    }
    if (requiredSkillsLower.size() > 0) {
      Integer matchPercentage =
        (commonSkillsCount * 100) / requiredSkillsLower.size();

      return matchPercentage;
    } else {
      return 0;
    }
  }
}