force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <description>a brief description about the candidate</description>
    <label>About</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Candidate_Email__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>email of the candidate(unique identifier)</description>
    <inlineHelpText>Your Email address</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city where the candidate is currently residing</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/CTC__c.field-meta.xml
<CustomField>
    <fullName>CTC__c</fullName>
    <inlineHelpText>Your CTC in LPA</inlineHelpText>
    <label>CTC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <inlineHelpText>Add Experience</inlineHelpText>
    <label>Total Experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/ParsedSkills__c.field-meta.xml
<CustomField>
    <fullName>ParsedSkills__c</fullName>
    <label>ParsedSkills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <description>Picture of the candidate</description>
    <label>Profile Picture</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>skills that would be entered by the candidate</description>
    <inlineHelpText>Enter Comma separated values</inlineHelpText>
    <label>Skills</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidate_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <description>The total work experience of the candidate which includes</description>
    <label>Work Experience</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experience</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <label>Candidate Name</label>
    <referenceTo>Candidate_Details__c</referenceTo>
    <relationshipLabel>Work Experience</relationshipLabel>
    <relationshipName>Work_Experience</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>city where the candidate worked</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>country where the city was located</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>Skills that the candidate gained at the job</description>
    <label>Skills</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/resumeparserController.cls
public with sharing class resumeparserController {
    public String userId;
    public String getuserId(){
        return userId;
    }
    public void setuserId(String userId){
        this.userId = userId;
    }
    public String acceptedFormats { get; set; } 
    public String parsedText { get; set; }
    public List<String> acceptedFormats() {
        return new List<String>{'.pdf'};
            }
    public String base64;
    public String getBase64(){
        return base64;
    }
    public void setbase64(String base64){
        this.base64 = base64;
    }
    public String fileName {get; set;}
    public Boolean uploadSuccess { get; set; }
    public void passUserId() {
        Candidate_Details__c candidateId = [SELECT Id FROM Candidate_Details__c WHERE User__c = :userId LIMIT 1];
        //perform multiple resume handling operation in this block 
    }
    public void saveFile(){
        Candidate_Details__c candidateId = [SELECT Id FROM Candidate_Details__c WHERE User__c = :userId LIMIT 1];    
        if(candidateId != null){
            // Query for existing ContentDocumentLinks related to the candidate
            List<ContentDocumentLink> existingContentDocLinks = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :candidateId.Id Limit 50000];
            if(!existingContentDocLinks.isEmpty()){
                // Delete existing attachments
                List<Id> contentDocumentIdsToDelete = new List<Id>();
                for(ContentDocumentLink cdLink : existingContentDocLinks){
                    contentDocumentIdsToDelete.add(cdLink.ContentDocumentId);
                }
                try {
                    delete [SELECT Id FROM ContentDocument WHERE Id IN :contentDocumentIdsToDelete];
                } catch(Exception e) {
                    throw new AuraHandledException(e.getMessage());
                }
            }
            // Create new attachment
            ContentVersion newContentVersion = new ContentVersion();																	
            newContentVersion.Title = this.fileName;
            newContentVersion.VersionData = EncodingUtil.base64decode(this.base64);
            newContentVersion.PathOnClient = fileName;
            insert newContentVersion;
            
            // Create new ContentDocumentLink
            ContentDocumentLink newContentDocLink = new ContentDocumentLink();
            newContentDocLink.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :newContentVersion.Id].ContentDocumentId;
            newContentDocLink.LinkedEntityId = candidateId.Id;
            insert newContentDocLink;
            uploadSuccess = true;
        } else {
            // System.debug('Candidate not found');
        }
    }
    public void updateParsedSkillsVF() {
        try {
            Candidate_Details__c candidateId = [SELECT Id, ParsedSkills__c FROM Candidate_Details__c WHERE User__c = :userId LIMIT 1];
            if(candidateId != null){
                candidateId.ParsedSkills__c = parsedText;
                update candidateId;
            }
        } catch (Exception e) {
            // Handle errors appropriately, e.g., display error message to user
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static Candidate_Details__c getData(Id userId) {
        try{
            List<Candidate_Details__c> currentCandidate = [SELECT Id, Profile_Picture__c, Name, Candidate_Email__c, CTC__c, Date_of_birth__c, About__c, Phone_Number__c, Skills__c, Experience__c, City__c, Country__c,
                                                           (SELECT Id, Name, Organisation__c, From_Date__c, To_Date__c, City__c, Country__c FROM Work_Experience__r ORDER BY From_Date__c DESC) FROM Candidate_Details__c WHERE User__c = :userId LIMIT 1]; 
            if (!currentCandidate.isEmpty()){
                return currentCandidate[0];
            } else {
                return new Candidate_Details__c();
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}