force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/Candidate_Email__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>email of the candidate(unique identifier)</description>
    <inlineHelpText>Your Email address</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CandidateSignUpController.cls
/**
 * An apex page controller that supports self registration of users in communities that allow self registration
 */
public class CandidateSignUpController {
  public String firstName { get; set; }
  public String lastName { get; set; }
  public String email { get; set; }
  public String password {
    get;
    set {
      password = value == null ? value : value.trim();
    }
  }
  public String confirmPassword {
    get;
    set {
      confirmPassword = value == null ? value : value.trim();
    }
  }

  public CandidateSignUpController() {
    String expid = ApexPages.currentPage().getParameters().get('expid');
    if (expId != null) {
      Site.setExperienceId(expId);
    }
  }

  private boolean isValidPassword() {
    return password == confirmPassword;
  }

  public PageReference registerUser() {
    PageReference pageRef = new PageReference('startUrl');
    system.debug('inside method');
    Candidate_Details__c existingCandidate = [SELECT Id FROM Candidate_Details__c WHERE Candidate_Email__c = :email LIMIT 1];
    
    if(existingCandidate != null) {
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'An account with this email already exists.'));
        return null; 
    }
    Candidate_Details__c candidate = new Candidate_Details__c();
    string username = email;

    candidate.Candidate_Email__c = username;
    candidate.Password__c = password;
    candidate.Name = firstName + ' ' + lastName;

    try {
      insert candidate;
      return pageRef;
    } catch (DMLException ex) {
      throw new AuraHandledException(ex.getMessage());
    }
  }
}