force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city where the candidate is currently residing</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Prefer Not to say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Name__c/Company_Name__c.object-meta.xml
<CustomObject>
    <label>Company Name</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Mechanics</fullName>
            </value>
            <value>
                <fullName>Medicine</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Leadership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Title_of_position__c.field-meta.xml
<CustomField>
    <fullName>Title_of_position__c</fullName>
    <label>Title of position</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/Job_Applicants__c.object-meta.xml
<CustomObject>
    <description>A junction object to link job__c and candidate_Details__c objects</description>
    <label>Job Applicants</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Applicants__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Decides the status of the applicant</description>
    <label>Application Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <label>CandidateId</label>
    <referenceTo>Candidate_Details__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <description>A master detail relation between job object and job_applicants object</description>
    <label>Job_Id</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/analyticsDatasets.cls
/**
 * @description       : this class includes datasets for the analytics component
 * @author            : Rudransh Shukla
 * @group             :
 * @last modified on  : 04-12-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public with sharing class analyticsDatasets {
  public class DataSet {
    @AuraEnabled
    public String label { get; set; }
    @AuraEnabled
    public Integer count { get; set; }

    public DataSet(String label, Integer count) {
      this.label = label;
      this.count = count;
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<DataSet> getApplicantDataset(string userId) {
    List<DataSet> dataSet = new List<DataSet>();
    user u = [select companyName from user where id = :userId limit 1];
    string companyname = u.CompanyName;

    try {
      List<Id> jobIdList = new List<Id>();
      for (Job__c job : [SELECT Id FROM Job__c where Company_Name__c = :companyname]) {
        jobIdList.add(job.Id);
      }

      List<Id> jobApplicantIdList = new List<Id>();
      for (Job_Applicants__c jobApplicant : [
        SELECT CandidateId__c
        FROM Job_Applicants__c
        WHERE Job_Id__c IN :jobIdList
      ]) {
        jobApplicantIdList.add(jobApplicant.CandidateId__c);
      }
      List<AggregateResult> results = [
        SELECT COUNT(Id) cnt, City__c
        FROM Candidate_Details__c
        WHERE Id IN :jobApplicantIdList
        GROUP BY City__c
      ];
      for (AggregateResult ar : results) {
        String City = (String) ar.get('City__c');
        Integer total = (Integer) ar.get('cnt');
        dataSet.add(new DataSet(City, total));
      }
    } catch (Exception e) {
      System.debug(
        'Error--------> ' + e.getMessage() + ' at line----> ' + e.getLineNumber()
      );
    }
    return dataSet;
  }

  @AuraEnabled(cacheable=true)
  public static List<DataSet> AgeWithNumberOfApplicants(string userId) {
    List<DataSet> dataset = new List<DataSet>();
    
    user u = [select companyName from user where id = :userId limit 1];
    string companyname = u.CompanyName;

    try {
      List<Id> jobIdList = new List<Id>();
      for (Job__c job : [SELECT Id FROM Job__c WHERE status__c = 'Completed' AND Company_Name__c = :companyname]) {
        jobIdList.add(job.Id);
      }

      List<Id> jobApplicantIdList = new List<Id>();
      for (Job_Applicants__c jobApplicant : [
        SELECT CandidateId__c
        FROM Job_Applicants__c
        WHERE Job_Id__c IN :jobIdList
      ]) {
        jobApplicantIdList.add(jobApplicant.CandidateId__c);
      }

      List<Date> dobList = new List<Date>();

      for (Candidate_Details__c candidate : [
        SELECT Date_of_birth__c
        FROM Candidate_Details__c
        WHERE Date_of_birth__c != NULL AND Id IN :jobApplicantIdList
      ]) {
        dobList.add(candidate.Date_of_birth__c);
      }

      Map<String, Integer> ageMap = new Map<String, Integer>();

      for (Date dob : dobList) {
        String ageGroup = calculateAge.calculateAgeMethod(dob);
        if (ageMap.containsKey(ageGroup)) {
          ageMap.put(ageGroup, ageMap.get(ageGroup) + 1);
        } else {
          ageMap.put(ageGroup, 1);
        }
      }

      for (String age : ageMap.keySet()) {
        dataset.add(new DataSet(age, ageMap.get(age)));
      }
    } catch (Exception e) {
      System.debug(
        'Error--------> ' + e.getMessage() + ' -------> ' + e.getLineNumber()
      );
    }
    return dataset;
  }
  @AuraEnabled(cacheable=true)
  public static List<DataSet> applicantGender(string userId) {
    List<DataSet> dataset = new List<DataSet>();
    user u = [select companyName from user where id = :userId limit 1];
    string companyname = u.CompanyName;
    try {
      List<Id> jobIdList = new List<Id>();
      for (Job__c job : [SELECT Id FROM Job__c WHERE status__c = 'Completed' AND Company_Name__c = :companyname]) {
        jobIdList.add(job.Id);
      }
      List<Id> jobApplicantIdList = new List<Id>();
      for (Job_Applicants__c jobApplicant : [
        SELECT CandidateId__c
        FROM Job_Applicants__c
        WHERE Job_Id__c IN :jobIdList
      ]) {
        jobApplicantIdList.add(jobApplicant.CandidateId__c);
      }

      list<AggregateResult> listOfGender = [
        SELECT count(id) cnt, Gender__c
        FROM Candidate_Details__c
        WHERE id IN :jobApplicantIdList
        GROUP BY Gender__c
      ];

      for (AggregateResult result : listOfGender) {
        String gender = (string) result.get('Gender__c');
        Integer count = (integer) result.get('cnt');
        dataset.add(new dataset(gender, count));
      }
    } catch (Exception e) {
      System.debug(
        'Error--------> ' + e.getMessage() + ' -------> ' + e.getLineNumber()
      );
    }
    return dataset;
  }

  @AuraEnabled(cacheable=true)
  public static list<dataset> industryJobsDataset(string userId) {
    user u = [select companyName from user where id = :userId limit 1];
    string companyname = u.CompanyName;
    List<DataSet> dataset = new List<DataSet>();
    try {
      list<AggregateResult> results = [
        SELECT count(id) cnt, Industry__c
        FROM Job__c
        WHERE status__c = 'Completed' AND Company_Name__c =:companyname
        GROUP BY Industry__c
      ];
      for (AggregateResult result : results) {
        string Industry = (string) result.get('Industry__c');
        integer count = (integer) result.get('cnt');
        dataset.add(new dataset(Industry, count));
      }
    } catch (Exception e) {
      System.debug(
        'Error--------> ' + e.getMessage() + ' -------> ' + e.getLineNumber()
      );
    }
    return dataset;
  }
  @AuraEnabled(cacheable=true)
  public static List<Dataset> numberOfApplicantsVsJobs(string userId) {
    user u = [select companyName from user where id = :userId limit 1];
    string companyname = u.CompanyName;
    List<Dataset> dataset = new List<Dataset>();
    try {
      List<Id> jobIdList = new List<Id>();
      for (Job__c job : [SELECT Id FROM Job__c WHERE Status__c = 'Completed' AND Company_Name__c =:companyname]) {
        jobIdList.add(job.Id);
      }

      List<Job__c> jobNames = [
        SELECT Title_of_position__c, Id
        FROM Job__c
        WHERE Id IN :jobIdList
      ];

      Map<Id, Integer> jobApplicantsCountMap = new Map<Id, Integer>();
      for (AggregateResult aggResult : [
        SELECT Job_Id__c, COUNT(Id) applicantsCount
        FROM Job_Applicants__c
        WHERE Job_Id__c IN :jobIdList
        GROUP BY Job_Id__c
      ]) {
        jobApplicantsCountMap.put(
          (Id) aggResult.get('Job_Id__c'),
          (Integer) aggResult.get('applicantsCount')
        );
      }
      for (Job__c job : jobNames) {
        Integer applicantsCount = jobApplicantsCountMap.containsKey(job.Id)
          ? jobApplicantsCountMap.get(job.Id)
          : 0;
        if (applicantsCount > 0) {
          dataset.add(new Dataset(job.Title_of_position__c, applicantsCount));
        }
      }
    } catch (Exception e) {
      System.debug(
        'Error--------> ' + e.getMessage() + ' -------> ' + e.getLineNumber()
      );
    }
    return dataset;
  }

  @AuraEnabled(cacheable=true)
  public static list<dataset> numberOfApplicantsShortlistedAndRejected(string userId) {

    user u = [select companyName from user where id = :userId limit 1];
    string companyname = u.CompanyName;

    List<Dataset> dataset = new List<Dataset>();
    try {
      list<AggregateResult> results = [
        SELECT count(id) cnt, Application_Status__c
        FROM Job_Applicants__c where Job_Id__c in (select id from Job__c where Company_Name__c = :companyname)
        GROUP BY Application_Status__c
      ];

      for (AggregateResult result : results) {
        string status = (string) result.get('Application_Status__c');
        integer count = (integer) result.get('cnt');
        dataset.add(new dataset(status, count));
      }
    } catch (Exception e) {
      System.debug(
        'Error--------> ' + e.getMessage() + ' -------> ' + e.getLineNumber()
      );
    }
    return dataset;
  }
}