force-app/main/default/objects/Candidate_Details__c/Candidate_Details__c.object-meta.xml
<CustomObject>
    <label>Candidate Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Details__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city where the candidate is currently residing</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Details__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>skills that would be entered by the candidate</description>
    <inlineHelpText>Enter Comma separated values</inlineHelpText>
    <label>Skills</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <description>The total work experience of the candidate which includes</description>
    <label>Work Experience</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experience</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <label>Candidate Name</label>
    <referenceTo>Candidate_Details__c</referenceTo>
    <relationshipLabel>Work Experience</relationshipLabel>
    <relationshipName>Work_Experience</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>city where the candidate worked</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>country where the city was located</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Is_Current_Company__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if it&apos;s you are currently working here.</description>
    <inlineHelpText>Check if it&apos;s you are currently working here.</inlineHelpText>
    <label>Is Current Company?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>Skills that the candidate gained at the job</description>
    <label>Skills</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkExperienceTriggerHandlerTest.cls
@isTest
private class WorkExperienceTriggerHandlerTest {
    @isTest
    static void testCurrentCompanyLogic() {
        
        User user = TestDataFactory.createDummyUser();

        Candidate_Details__c candidate = TestDataFactory.createCandidateDetails();

        List<Work_Experience__c> workExpList = new List<Work_Experience__c>{
            new Work_Experience__c(
                CandidateId__c = candidate.Id,
                City__c = 'City1',
                Country__c = 'Country1',
                Name = 'Work Experience 1',
                From_Date__c = Date.newInstance(2020, 1, 1),
                To_Date__c = Date.newInstance(2022, 12, 31),
                Is_Current_Company__c = true,
                Organisation__c = 'Company A',
                Skills__c = 'Java, SQL'
            ),
            new Work_Experience__c(
                CandidateId__c = candidate.Id,
                City__c = 'City2',
                Country__c = 'Country2',
                Name = 'Work Experience 2',
                From_Date__c = Date.newInstance(2023, 1, 1),
                To_Date__c = Date.newInstance(2024, 12, 31),
                Is_Current_Company__c = true, 
                Organisation__c = 'Company B',
                Skills__c = 'Java, SQL'
            )
        };
        insert workExpList;
        List<Work_Experience__c> currentWorkExp = [SELECT Id FROM Work_Experience__c WHERE CandidateId__c = :candidate.Id AND Is_Current_Company__c = true Limit 1];
        System.assertEquals(1, currentWorkExp.size(), 'More than one work experience is marked as current');
        Work_Experience__c olderWorkExp = [SELECT Id, Is_Current_Company__c FROM Work_Experience__c WHERE CandidateId__c = :candidate.Id AND Is_Current_Company__c = false LIMIT 1];
        System.assertNotEquals(null, olderWorkExp, 'No older work experience marked as not current');
    }
}