force-app/main/default/objects/Company_Name__c/Company_Name__c.object-meta.xml
<CustomObject>
    <label>Company Name</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>no experience needed</fullName>
            </value>
            <value>
                <fullName>less than 1 year</fullName>
            </value>
            <value>
                <fullName>1 to 3 years</fullName>
            </value>
            <value>
                <fullName>3 to 5 years</fullName>
            </value>
            <value>
                <fullName>more than 5 years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Publish_end_date__c.field-meta.xml
<CustomField>
    <fullName>Publish_end_date__c</fullName>
    <label>Publish end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Publish_start_date__c.field-meta.xml
<CustomField>
    <fullName>Publish_start_date__c</fullName>
    <label>Publish start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Title_of_position__c.field-meta.xml
<CustomField>
    <fullName>Title_of_position__c</fullName>
    <label>Title of position</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetPostedJobList.cls
/**
 * @description       : to retrive the list of all the jobs posted by HR
 * @author            : Rudransh Shukla
 * @group             :
 * @last modified on  : 02-05-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/

public with sharing class GetPostedJobList {
    @AuraEnabled(cacheable=true)
  public static list<job__c> getPostedJobList() {
    system.debug('start');

    list<job__c> postedJobList = new List<job__c>();

    for (job__c job : [
      SELECT
        Title_of_position__c,
        Salary__c,
        Experience__c,
        Company_Name__c,
        City__c,
        Country__c,
        Publish_end_date__c,
        Publish_start_date__c,
        id
      FROM Job__c
      WHERE Status__c = 'Completed'
    ]) {
      postedJobList.add(job);
    }
    system.debug('postedJobList------->'+postedJobList);
    return postedJobList;
  }
}