force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <description>The total work experience of the candidate which includes</description>
    <label>Work Experience</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experience</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <label>Candidate Name</label>
    <referenceTo>Candidate_Details__c</referenceTo>
    <relationshipLabel>Work Experience</relationshipLabel>
    <relationshipName>Work_Experience</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Is_Current_Company__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if it&apos;s you are currently working here.</description>
    <inlineHelpText>Check if it&apos;s you are currently working here.</inlineHelpText>
    <label>Is Current Company?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WorkExperienceTriggerHandler.cls
/**
 * @description       : handler class for work experience trigger
 * @author            : Sagar Medatwal
 * @group             : 
 * @last modified on  : 03-29-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class WorkExperienceTriggerHandler {
    public static void checkIsCurrentCompany(List<Work_Experience__c> workExpList, Map<Id, Work_Experience__c> workExpMap) {
        if (workExpList != null && !workExpList.isEmpty()) {
            Map<Id, Work_Experience__c> candidateCurrentWorkMap = new Map<Id, Work_Experience__c>();
            for(Work_Experience__c work : workExpList){
                if(workExpMap != null){
                    Work_Experience__c currentWork = workExpMap.get(work.Id);
                    if((work.Is_Current_Company__c != currentWork.Is_Current_Company__c) && work.Is_Current_Company__c == true){
                        candidateCurrentWorkMap.put(work.CandidateId__c, work);
                    }
                }else{
                    candidateCurrentWorkMap.put(work.CandidateId__c, work);
                }
            }
            if (!candidateCurrentWorkMap.isEmpty()) {
                List<Work_Experience__c> allCurrentWorkExp = [SELECT Id, CandidateId__c FROM Work_Experience__c WHERE CandidateId__c IN :candidateCurrentWorkMap.keySet() AND Is_Current_Company__c = true];
                if (!allCurrentWorkExp.isEmpty()) {
                    for (Work_Experience__c currentWorkExp : allCurrentWorkExp) {
                        Work_Experience__c latestCurrentWork = candidateCurrentWorkMap.get(currentWorkExp.CandidateId__c);
                        if (latestCurrentWork != null && latestCurrentWork.Id != currentWorkExp.Id) {
                            currentWorkExp.Is_Current_Company__c = false;
                        }
                    }
                    update allCurrentWorkExp;
                }
            }
        }
    }
}